name: new-ci-test
on:
  schedule:
    - cron: "*/10 * * * *"
  push:
    branches: [chain_agnostic_tests]
  workflow_dispatch:

jobs:
  integration:
    runs-on: pierre-l
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - name: install hurl
        run: |
          version=4.1.0
          curl --location --remote-name "https://github.com/Orange-OpenSource/hurl/releases/download/${version}/hurl_${version}_amd64.deb"
          sudo apt-get update && sudo apt-get install -y ./hurl_${version}_amd64.deb

      - name: build beerus
        run: cargo build -p beerus-cli --release

      - name: start beerus RPC on MAINNET
        env:
          BEERUS_VERSION: "ci"
          NETWORK: "mainnet"
          ETH_EXECUTION_RPC: ${{ secrets.ETH_EXECUTION_RPC_MAINNET }}
          STARKNET_RPC: ${{ secrets.STARKNET_RPC_0_6_0_MAINNET }}
        run: ./target/release/beerus &

      - name: run integration test on MAINNET
        run: cargo test --package --features integration-tests

      - name: stop RPC
        run: kill $(lsof -t -i:3030)
