name: rust-integration-tests-alchemy
on:
  schedule:
    - cron: "*/30 * * * *"
  push:
  workflow_dispatch:

jobs:
  integration:
    runs-on: alchemy
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - name: build beerus
        run: cargo build -p beerus-cli --release

      - name: start beerus RPC on MAINNET
        env:
          ETH_EXECUTION_RPC: ${{ secrets.ETH_EXECUTION_RPC_MAINNET }}
          STARKNET_RPC: ${{ secrets.STARKNET_RPC_0_6_0_MAINNET_ALCHEMY }}
        # Start Beerus, then try to reach the port every second for 60 seconds.
        run: ./target/release/beerus & ./scripts/wait-for-it.sh localhost:3030 -t 120

      - name: run integration test on MAINNET
        run: cargo test --package beerus-rpc --features integration-tests

      - name: stop RPC
        run: kill $(lsof -t -i:3030)
 