name: rust-integration-tests-chainstack
on:
  schedule:
    - cron: "* */2 * * *"
  push:
  workflow_dispatch:

jobs:
  integration:
    runs-on: pierre-l
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - name: build beerus
        run: cargo build -p beerus-cli --release

      - name: start beerus RPC on MAINNET
        env:
          BEERUS_VERSION: "ci"
          NETWORK: "mainnet"
          ETH_EXECUTION_RPC: ${{ secrets.ETH_EXECUTION_RPC_MAINNET }}
          STARKNET_RPC: ${{ secrets.STARKNET_RPC_0_6_0_MAINNET_CHAINSTACK }}
          RPC_ADDR: 127.0.0.1:${{ vars.IT_PORT_CHAINSTACK }}
        run: ./target/release/beerus & for i in {1..30}; do timeout 1 bash -c "echo > /dev/tcp/localhost/${{ vars.IT_PORT_CHAINSTACK }}" 2> /dev/null && break || sleep 1; done

      - name: run integration test on MAINNET
        env:
          RPC_ADDR: 127.0.0.1:${{ vars.IT_PORT_CHAINSTACK }}
        run: cargo test --package beerus-rpc --features integration-tests

      - name: stop RPC
        run: kill $(lsof -t -i:${{ vars.IT_PORT_CHAINSTACK }})
 